const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Plugins.Audio,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Keyboard.Cnds.OnAnyKeyReleased,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.IsOverlapping
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Audio: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{player: 0},
	{Keyboard: 0},
	{Jumpthru: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{item_test: 0},
	{playerHolding: 0},
	{Pin: 0},
	{Sprite6: 0},
	{Bullet: 0},
	{bullet: 0},
	{movement: 0},
	{MoveTo: 0},
	{enemy: 0},
	{movementSwitch: 0},
	{Sprite3: 0},
	{victoryBox: 0}
];

self.InstanceType = {
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	item_test: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	bullet: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	movementSwitch: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	victoryBox: class extends self.ISpriteInstance {}
}